version: '2'

services:
  app:
    container_name: ts-spa-boilerplate
    build: .
    command: "npm start"
    ports:
      - "3000:3000"
    # volumes:
    #  - ./srv
    environment:
      - PORT=3000
